### ISSUE TITLE
So... What's going on?

### ISSUE THREAD

**Issue by xdays** [kotfu/markdown-enml#1]
:)

**Comment by kotfu** [comment]
Well, I am a heavy user of evernote, but I don't love their text editor. I also love writing in markdown. So I hope to build a script (probably in python or ruby) which can take a markdown document and a style sheet as input, and spit out ENML (ever note's flavor of xml) for a single note. Using that core script, I can then build a nice service for OS X (my operating system of choice) to call that script from Finder and add a new note. Because the core script will be cross platform, it should be relatively easy to make it work on Windows or Linux.

I have written no code yet, because I keep running out of spare time to work on this.

**Comment by xdays** [comment]
That's exactly what I want too. In my opinion, since ENML is just a subset of XHTML, we may just wrap the rendered HTML from Markdown into en the `en-note` tag. I'll try it when I have time.

**Comment by kotfu** [comment]
OK, I've got a working python library which does this. Next I'm going to create a command line tool which can take a markdown file, convert it to enml, and then add it to evernote.
